remote_theme: bruno-chanrio/materialize-jekyll@1.2
plugins:
- jekyll-remote-theme
- jekyll-last-modified-at
- jemoji

author: 

head-title: Listas IPTV
title: Listas IPTV

baseurl: ""    # the subpath of your site, "/blog"
url: ""

# footer 


#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "teal darken-3"
head-theme-color: "#009688"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "teal darken-3"
footer-button-color: "teal darken-3"
footer-link-color: "teal text-lighten-1"

share-button-color: "teal darken-4"
share-button-small-color: ""

##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt
