remote_theme: brunochanrio/material-jekyll-chanrio@2025.04.14_v2
plugins:
- jekyll-remote-theme

title: Listas IPTV
author: Listas IPTV



baseurl: ""
color: "#26a69a"
head-theme-color: "#26a69a"
accentColor: teal
themeColor: teal
fixedNav: 'true' # true or false

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
